export const authState = {
    uuid : '',
    username : '',
    changeuser : false,
    email : '',
    emailverified : 0,
    changeemail: false,
    mobile : '',
    mobileverified : 0,
    password: '',
    newpassword :'',
    peek : false,
    peeknp :false,
    donation : -1,
    rememberme : false,
    paymentSuccess : false,
    receiptUrl : '',
    registered : false,
    signedin : false,
}
