# Set the base image to node:16-alpine
FROM node:16-alpine as build

# Specify where our app will live in the container
WORKDIR /app

# Copy the site to the container
COPY . /app/

# Prepare the container for building React
RUN npm install -g http-server
# We want the production version
CMD ["http-server"]
